// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/container/src/Aside/index.vue')['default']
    ChooseArea: typeof import("./src/components/chooseArea/src/index.vue")["default"]
    ChooseIcon: typeof import("./src/components/chooseIcon/src/index.vue")["default"]
    ContainerSrc: typeof import("./src/components/container/src/index.vue")["default"]
    ContainerSrcAside: typeof import("./src/components/container/src/Aside/index.vue")["default"]
    ContainerSrcNavHeader: typeof import("./src/components/container/src/NavHeader/index.vue")["default"]
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import("element-plus/es")["ElIcon"]
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavHeader: typeof import('./src/components/container/src/NavHeader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/chooseArea/src/index.vue')['default']
  }
}
